In [49]:
#NLP we need 2 frameworks NLTK and SPACY

#NLTK --> Natural Language Toolkit

In [50]:
import nltk
nltk.download('punkt')
#we need to load the data and preprocess the data then develop the NLP model

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

Collect the data

In [51]:
text = """Manually analyzing hundreds of unstructured text-based data sources is tedious and time-consuming. What's worse is that since it's in text format, you know this process can be made easier, but you're unsure how to do it. If you’re in a data-driven company that relies on such data sources to make critical decisions to optimize and improve your customer experience processes, keep reading.And he's right. Too often, we get stuck in the DRIP syndrome where we're happily generating data—but can't generate meaningful insights from them. Also, when you consider that 80% to 90% of data is unstructured,  there’s so much potential waiting to be unlocked.In this article, we’ll discuss the concept of textual data and how you can use it to extract valuable insights for your customer support operations."""
print(text)

Manually analyzing hundreds of unstructured text-based data sources is tedious and time-consuming. What's worse is that since it's in text format, you know this process can be made easier, but you're unsure how to do it. If you’re in a data-driven company that relies on such data sources to make critical decisions to optimize and improve your customer experience processes, keep reading.And he's right. Too often, we get stuck in the DRIP syndrome where we're happily generating data—but can't generate meaningful insights from them. Also, when you consider that 80% to 90% of data is unstructured,  there’s so much potential waiting to be unlocked.In this article, we’ll discuss the concept of textual data and how you can use it to extract valuable insights for your customer support operations.


#Tokenization = it means understanding the sentences and words from given data

In [52]:
## Sentence Tokenization
from nltk.tokenize import sent_tokenize  #sentence tokenization

total_sentence = sent_tokenize(text)

print(total_sentence)

print(f'total number of sentences in data : {len(total_sentence)}')

['Manually analyzing hundreds of unstructured text-based data sources is tedious and time-consuming.', "What's worse is that since it's in text format, you know this process can be made easier, but you're unsure how to do it.", "If you’re in a data-driven company that relies on such data sources to make critical decisions to optimize and improve your customer experience processes, keep reading.And he's right.", "Too often, we get stuck in the DRIP syndrome where we're happily generating data—but can't generate meaningful insights from them.", 'Also, when you consider that 80% to 90% of data is unstructured,  there’s so much potential waiting to be unlocked.In this article, we’ll discuss the concept of textual data and how you can use it to extract valuable insights for your customer support operations.']
total number of sentences in data : 5


In [53]:
#Word tokenize

from nltk.tokenize import word_tokenize
total_word = word_tokenize(text)

print(total_word)

print(f'total words in data : {len(total_word)}')


['Manually', 'analyzing', 'hundreds', 'of', 'unstructured', 'text-based', 'data', 'sources', 'is', 'tedious', 'and', 'time-consuming', '.', 'What', "'s", 'worse', 'is', 'that', 'since', 'it', "'s", 'in', 'text', 'format', ',', 'you', 'know', 'this', 'process', 'can', 'be', 'made', 'easier', ',', 'but', 'you', "'re", 'unsure', 'how', 'to', 'do', 'it', '.', 'If', 'you', '’', 're', 'in', 'a', 'data-driven', 'company', 'that', 'relies', 'on', 'such', 'data', 'sources', 'to', 'make', 'critical', 'decisions', 'to', 'optimize', 'and', 'improve', 'your', 'customer', 'experience', 'processes', ',', 'keep', 'reading.And', 'he', "'s", 'right', '.', 'Too', 'often', ',', 'we', 'get', 'stuck', 'in', 'the', 'DRIP', 'syndrome', 'where', 'we', "'re", 'happily', 'generating', 'data—but', 'ca', "n't", 'generate', 'meaningful', 'insights', 'from', 'them', '.', 'Also', ',', 'when', 'you', 'consider', 'that', '80', '%', 'to', '90', '%', 'of', 'data', 'is', 'unstructured', ',', 'there', '’', 's', 'so', 'much

In [54]:
#remove unwanted stuff : - punctutations

text #to develop NPL application we need keep only words other than everything should be removed

"Manually analyzing hundreds of unstructured text-based data sources is tedious and time-consuming. What's worse is that since it's in text format, you know this process can be made easier, but you're unsure how to do it. If you’re in a data-driven company that relies on such data sources to make critical decisions to optimize and improve your customer experience processes, keep reading.And he's right. Too often, we get stuck in the DRIP syndrome where we're happily generating data—but can't generate meaningful insights from them. Also, when you consider that 80% to 90% of data is unstructured,  there’s so much potential waiting to be unlocked.In this article, we’ll discuss the concept of textual data and how you can use it to extract valuable insights for your customer support operations."

In [55]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [56]:
clean_text =[]

for i in text:
  if i not in string.punctuation:
    clean_text.append(i)

proper_text = ''.join(clean_text)
print(proper_text)

Manually analyzing hundreds of unstructured textbased data sources is tedious and timeconsuming Whats worse is that since its in text format you know this process can be made easier but youre unsure how to do it If you’re in a datadriven company that relies on such data sources to make critical decisions to optimize and improve your customer experience processes keep readingAnd hes right Too often we get stuck in the DRIP syndrome where were happily generating data—but cant generate meaningful insights from them Also when you consider that 80 to 90 of data is unstructured  there’s so much potential waiting to be unlockedIn this article we’ll discuss the concept of textual data and how you can use it to extract valuable insights for your customer support operations


In [57]:
#lower the text
proper_text = proper_text.lower()

print(proper_text)

manually analyzing hundreds of unstructured textbased data sources is tedious and timeconsuming whats worse is that since its in text format you know this process can be made easier but youre unsure how to do it if you’re in a datadriven company that relies on such data sources to make critical decisions to optimize and improve your customer experience processes keep readingand hes right too often we get stuck in the drip syndrome where were happily generating data—but cant generate meaningful insights from them also when you consider that 80 to 90 of data is unstructured  there’s so much potential waiting to be unlockedin this article we’ll discuss the concept of textual data and how you can use it to extract valuable insights for your customer support operations


In [58]:
# removing stopwords ****
nltk.download('stopwords')
from nltk.corpus import stopwords


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [59]:
cleaned_text = []

for i in proper_text.split():
  if i not in stopwords.words('english'):
    cleaned_text.append(i)

final_data = ' '.join(cleaned_text)
print(final_data)


manually analyzing hundreds unstructured textbased data sources tedious timeconsuming whats worse since text format know process made easier youre unsure you’re datadriven company relies data sources make critical decisions optimize improve customer experience processes keep readingand hes right often get stuck drip syndrome happily generating data—but cant generate meaningful insights also consider 80 90 data unstructured there’s much potential waiting unlockedin article we’ll discuss concept textual data use extract valuable insights customer support operations


In [60]:
## Stemming & Lemmatization
#these 2 techniques are used to carry the  information how human brain  understands

#Stemming on data
from nltk.stem import PorterStemmer
stemming = PorterStemmer()
for i in final_data.split():
  print("Before Stemming : ", i , "------After stemming : ",stemming.stem(i))


Before Stemming :  manually ------After stemming :  manual
Before Stemming :  analyzing ------After stemming :  analyz
Before Stemming :  hundreds ------After stemming :  hundr
Before Stemming :  unstructured ------After stemming :  unstructur
Before Stemming :  textbased ------After stemming :  textbas
Before Stemming :  data ------After stemming :  data
Before Stemming :  sources ------After stemming :  sourc
Before Stemming :  tedious ------After stemming :  tediou
Before Stemming :  timeconsuming ------After stemming :  timeconsum
Before Stemming :  whats ------After stemming :  what
Before Stemming :  worse ------After stemming :  wors
Before Stemming :  since ------After stemming :  sinc
Before Stemming :  text ------After stemming :  text
Before Stemming :  format ------After stemming :  format
Before Stemming :  know ------After stemming :  know
Before Stemming :  process ------After stemming :  process
Before Stemming :  made ------After stemming :  made
Before Stemming :  eas

In [61]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [62]:
from nltk.stem import WordNetLemmatizer
lemmatization = WordNetLemmatizer()
for i in final_data.split():
  print("Before Lemmatization : ",i , "-------After Lemmaization : ", lemmatization.lemmatize(i))

Before Lemmatization :  manually -------After Lemmaization :  manually
Before Lemmatization :  analyzing -------After Lemmaization :  analyzing
Before Lemmatization :  hundreds -------After Lemmaization :  hundred
Before Lemmatization :  unstructured -------After Lemmaization :  unstructured
Before Lemmatization :  textbased -------After Lemmaization :  textbased
Before Lemmatization :  data -------After Lemmaization :  data
Before Lemmatization :  sources -------After Lemmaization :  source
Before Lemmatization :  tedious -------After Lemmaization :  tedious
Before Lemmatization :  timeconsuming -------After Lemmaization :  timeconsuming
Before Lemmatization :  whats -------After Lemmaization :  whats
Before Lemmatization :  worse -------After Lemmaization :  worse
Before Lemmatization :  since -------After Lemmaization :  since
Before Lemmatization :  text -------After Lemmaization :  text
Before Lemmatization :  format -------After Lemmaization :  format
Before Lemmatization :  know

In [63]:
from nltk.stem import WordNetLemmatizer
lemmatized_text = []
lemmatization = WordNetLemmatizer()
for i in final_data.split():
  lemmatized_text.append(lemmatization.lemmatize(i))
lemmatized_text = ' '.join(lemmatized_text)
print(lemmatized_text)

manually analyzing hundred unstructured textbased data source tedious timeconsuming whats worse since text format know process made easier youre unsure you’re datadriven company relies data source make critical decision optimize improve customer experience process keep readingand he right often get stuck drip syndrome happily generating data—but cant generate meaningful insight also consider 80 90 data unstructured there’s much potential waiting unlockedin article we’ll discus concept textual data use extract valuable insight customer support operation


In [64]:
#for converting text to numbers we can use Bag of Words , TF-IDF[Term frequency and Inverse Document Frequency] and Embeded techniques

In [65]:
#Bag of words:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer  # for bag of words

res = CountVectorizer()

values = res.fit_transform([lemmatized_text])
print(values.toarray())

[[1 1 1 1 1 1 1 1 1 1 1 2 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1
  1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1]]


In [66]:
## To make some difference between words we are gpoing to use TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

res = TfidfVectorizer()

values = res.fit_transform([lemmatized_text])

print(values.toarray())

[[0.09667365 0.09667365 0.09667365 0.09667365 0.09667365 0.09667365
  0.09667365 0.09667365 0.09667365 0.09667365 0.09667365 0.1933473
  0.48336824 0.09667365 0.09667365 0.09667365 0.09667365 0.09667365
  0.09667365 0.09667365 0.09667365 0.09667365 0.09667365 0.09667365
  0.09667365 0.09667365 0.09667365 0.09667365 0.1933473  0.09667365
  0.09667365 0.09667365 0.09667365 0.09667365 0.09667365 0.09667365
  0.09667365 0.09667365 0.09667365 0.09667365 0.09667365 0.1933473
  0.09667365 0.09667365 0.09667365 0.09667365 0.09667365 0.1933473
  0.09667365 0.09667365 0.09667365 0.09667365 0.09667365 0.09667365
  0.09667365 0.09667365 0.09667365 0.09667365 0.1933473  0.09667365
  0.09667365 0.09667365 0.09667365 0.09667365 0.09667365 0.09667365
  0.09667365 0.09667365]]


In [67]:
## Embedding Technique(*****):

import tensorflow
from tensorflow import keras
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences



In [68]:
#integer encode the documents
vocab_size = 100
encoded_doc = [one_hot(d, vocab_size)for d in lemmatized_text]
print(encoded_doc)

[[11], [84], [85], [91], [84], [59], [59], [98], [], [84], [85], [84], [59], [98], [55], [24], [85], [52], [], [32], [91], [85], [58], [56], [21], [58], [], [91], [85], [39], [57], [56], [91], [59], [57], [91], [56], [21], [58], [], [57], [21], [55], [57], [13], [84], [39], [21], [58], [], [58], [84], [57], [84], [], [39], [21], [91], [56], [59], [21], [], [57], [21], [58], [24], [21], [91], [39], [], [57], [24], [11], [21], [59], [21], [85], [39], [91], [11], [24], [85], [52], [], [60], [32], [84], [57], [39], [], [60], [21], [56], [39], [21], [], [39], [24], [85], [59], [21], [], [57], [21], [55], [57], [], [5], [21], [56], [11], [84], [57], [], [92], [85], [21], [60], [], [40], [56], [21], [59], [21], [39], [39], [], [11], [84], [58], [21], [], [21], [84], [39], [24], [21], [56], [], [98], [21], [91], [56], [21], [], [91], [85], [39], [91], [56], [21], [], [98], [21], [91], [61], [56], [21], [], [58], [84], [57], [84], [58], [56], [24], [34], [21], [85], [], [59], [21], [11], [40], 

In [69]:
print(len(encoded_doc))

558


In [70]:
#remove null values from encoded_doc

encoded_doc = [d for d in encoded_doc if d != [] * vocab_size]


In [71]:
print(encoded_doc)

[[11], [84], [85], [91], [84], [59], [59], [98], [84], [85], [84], [59], [98], [55], [24], [85], [52], [32], [91], [85], [58], [56], [21], [58], [91], [85], [39], [57], [56], [91], [59], [57], [91], [56], [21], [58], [57], [21], [55], [57], [13], [84], [39], [21], [58], [58], [84], [57], [84], [39], [21], [91], [56], [59], [21], [57], [21], [58], [24], [21], [91], [39], [57], [24], [11], [21], [59], [21], [85], [39], [91], [11], [24], [85], [52], [60], [32], [84], [57], [39], [60], [21], [56], [39], [21], [39], [24], [85], [59], [21], [57], [21], [55], [57], [5], [21], [56], [11], [84], [57], [92], [85], [21], [60], [40], [56], [21], [59], [21], [39], [39], [11], [84], [58], [21], [21], [84], [39], [24], [21], [56], [98], [21], [91], [56], [21], [91], [85], [39], [91], [56], [21], [98], [21], [91], [61], [56], [21], [58], [84], [57], [84], [58], [56], [24], [34], [21], [85], [59], [21], [11], [40], [84], [85], [98], [56], [21], [59], [24], [21], [39], [58], [84], [57], [84], [39], [21]

In [72]:
print(len(encoded_doc))

485


In [73]:
#learn with example

docs = ['Well done!',
'Good work',
'Great effort',
'nice work',
'Excellent!',
'Weak',
'Poor effort!',
'not good',
'poor work',
'Could have done better.']

labels = [1,1,1,1,1,0,0,0,0,0] # defining class labels

In [74]:
# integer encode the documents
vocab_size = 100
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[57, 7], [19, 14], [49, 8], [27, 14], [81], [3], [28, 8], [62, 19], [28, 14], [1, 50, 7, 32]]


In [75]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[57  7  0  0]
 [19 14  0  0]
 [49  8  0  0]
 [27 14  0  0]
 [81  0  0  0]
 [ 3  0  0  0]
 [28  8  0  0]
 [62 19  0  0]
 [28 14  0  0]
 [ 1 50  7 32]]


In [76]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential

In [77]:
from tensorflow.keras import layers

In [78]:
#define model
model = tf.keras.Sequential()
model.add(layers.Embedding(vocab_size,8,input_length = max_length))
model.add(layers.Flatten())
model.add(layers.Dense(1,activation = 'sigmoid'))

In [79]:
import numpy as np
labels=np.array(labels)

In [80]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
model.summary()
# fit the model
model.fit(padded_docs, labels, epochs=100, verbose=2)


Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 4, 8)              800       
                                                                 
 flatten_3 (Flatten)         (None, 32)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 833 (3.25 KB)
Trainable params: 833 (3.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/100
1/1 - 1s - loss: 0.6914 - acc: 0.6000 - 702ms/epoch - 702ms/step
Epoch 2/100
1/1 - 0s - loss: 0.6900 - acc: 0.6000 - 9ms/epoch - 9ms/step
Epoch 3/100
1/1 - 0s - loss: 0.6885 - acc: 0.6000 - 9ms/epoch - 9ms/step
Epoch 4/100
1/1 - 0s - loss: 0.6871 - acc: 0.5000 - 8ms/epoch - 8

In [81]:
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 89.999998
